### ISSUE TITLE
Bug: config_builder.rb:14: syntax error, unexpected ')'

### ISSUE THREAD

**Issue by ferreiro** [k0kubun/md2key#39]
Hello. I'm running the command `md2key test.md` with the following data example:

```md
# The presentation
@k0kubun

## Hello world
- I'm takashi kokubun
- This is a pen
  - Nested item is available

## How are you?
- I'm fine thank you
```

And... I created a `template.key` file in the same folder as test.md

However, the program fails with the following error:

```bash
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': /Library/Ruby/Gems/2.0.0/gems/md2key-0.8.2/lib/md2key/config_builder.rb:14: syntax error, unexpected ')' (SyntaxError)
/Library/Ruby/Gems/2.0.0/gems/md2key-0.8.2/lib/md2key/config_builder.rb:27: syntax error, unexpected keyword_end, expecting end-of-input
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/md2key-0.8.2/lib/md2key/cli.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/md2key-0.8.2/lib/md2key.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/md2key-0.8.2/exe/md2key:4:in `<top (required)>'
	from /usr/local/bin/md2key:23:in `load'
	from /usr/local/bin/md2key:23:in `<main>'
```

OS: MacOS Sierra
md2key version: 0.8.2 (latest)

Could you help?

**Comment by k0kubun** [comment]
Ah, umm, yes. md2key does only supports Ruby 2.1+ and macOS has Ruby 2.0 by default.

But I think md2key should support macOS's default Ruby. I'll consider to fix this.

**Comment by ferreiro** [comment]
@k0kubun Ok! Yeah. Would be cool to support the Ruby macOS's default version. I'll upgrade my ruby version to make this work. Thanks for your soon response! :).
